# Remove spurious sequences

# Load libraries
library(tidyverse)
library(seqinr)


#### Load and format ASV data ####
# Import melted ASV data
asv_melt <- read_tsv("output/melted/lp2017-2019watercolumn18s_melt_all.tsv", col_names = TRUE)

# Import alignment
# alignment <- read.fasta("output/fasta/lp2017-2019watercolumn18s_all_mafft.fasta", "DNA", as.string = TRUE, forceDNAtolower = FALSE)
# alignment <- tibble(asv_code = names(alignment),
#                     sequence = unlist(getSequence(alignment, as.string = TRUE)))


#### Remove potentially spurious ASVs ####
asvs_spurious <- c("GGGGAACTTACCTGGGCTTATGCACACGAGAGTGTCGTGCTGAGAGGCTCTAGACGATAGTGCAGTGAGTGGTGCATGGCCGTTTTCAACGTGTGGGGTGACTTTTTGGTTAATTCCTGTAATGTGTGAGGCCGAGGTTGCGACGAGCTGGAGGGGCTGAGATTGATTTGTAATTTGTTTCAGTCCGTGTGGATTTTGTTGCAGTTTTGAGCGCGGGAAGTGCTATTTTCGGCG",
                   "CAAATCTTACCAGACCCAGATGCTTTACGGAGCAACAGATTAAGAGTTCTTTTGCGATTGGGCAGTTGGTGGTGCATGGCCGCTCCTAGTTCGTGGTGTAAACTGTCTGCCTTATTGCGTTAACGAGCGAGACAACCGCCCTAATTTATTTTGGGGGAGCGCCAGCGTTGAGCTGGACGAACGCGGTTGCGCTAGCAGGTCTGTGATGCC",
                   "GGAAAACTTACCAGTCCCTCTAAGAAGTCACGTACGTATCATAGAGCACGCTGAACTATTTAGCAGGTCGAGGTCTCGTTCGTTAACGGAATTAACCAGACAAATCACTCCACCAACTAAAAACGGCCATGCACCACAACCCATAGAATCAAGAAAGGTCTTCAGCCTGTCAATCCTAACTATATATGGACCTGGAGTATCCGATGGAAGCGATGGAAGTTCGAGGCA",
                   "GGGGAGCTTACCGGGGCGTGTTGCGGGGTGAGTGGGGATCTGAGGGGTCTGCGCGAGTAGCAACAGGGTGGTGCATGGCCGCTTGCAACAAGTGGGGTGACCTTGTGGTTTGATCCCGGAACGGGTGAGGCGCGGGTGTTGACGAGTTTAGTGGCTGTGGTTTTTTTCTGTGGTTATGGACTGGTGGACGGACGGGCAGTGGGAAGCTGCAGGAAGAGGCGCG",
                   "GGGAAACTTACGTGGTCAGGACAGGAGAAGGATTGACAGATTGAAGTTCTTTCAAGATTTTTTGGGTGGTGGTGCATGGCCGTTCTTAGTTAGTGATGTGAATTGTCTGCTTTATTGCGATAACTAGCGAGACCACTGCGGCTTTGTACGACGACCGAGTGCGCAAGTGCTCGGCCGCTTCGTTATAGCCGGACAGCGGCGGTCACGCCGAGGAAGTTGGTGGCG",
                   "GGCATTCACCCGGCCACCATGAACATGGTCGTGGCGCTCAACATCGAAGGCACACTTTCCTCCGACGAGGAGGACATCGTGGCGGCGTTCATCAACGACGAACTCCGGGGCCGCGCCTACATCCGCTATTACCCCTCGGTGGACAAGTATCTCGCGCACCTGACCGTTTACGGCGATACGTCGGACTTGCTTGATCCGGTCCGTTTCCAGGTCTGTGATGCCC",
                   "GGGGAACTTACCTGGGCAGGATCTGCGGGAGAATGTCCGGCTGAGAGGGCGTACGTGATAGCGGAGAGAGTGGTGCATGGCCGTTTTCAACGTGTGGGGTGACTTATTGGTTAATTCCTTGAATGTGTGAGGCCGACGTTGCGACTGTGCCGGGGAGCGGGGAACTGTGAGCTGGTGAGTAGCGAGAGGGAGGGCGGCAAGCCCTGTGAAGTTGGCG",
                   "AAATAAACCAAGGTAACGGTGCTGGAGACAATCCTGTCTCCACTGATACTGCGGCTCCAGGAAATGGCAGTGTTACAGAAGTAACCACTGGGACAGTTACAGTCGGTAGCGATGTTGATAACACCTTACTTTACGACAGTCCATTGACTGGTAAAAAGTATTATGTCAAAACAGTTACCAAACAGCCGGGAGTGGTATTTCCCTATGATGTGGCCACAGTAGCACCACAGAATGGATTAACCGT",
                   "GGAAAATTTACCAGGACCGACACGGTTAAGATTGACACTGTTAAGCAGTTTCTTGACGCAGTGAATGGTGGTGCATGGCCGCTCGTAGCTCGTGGAGTGATTTGTCTGCTCTACTGCGGTAACGGGCGAGATTCTTAGGGGTTGTTGGTGACGCTGGAGCTGCGGTTGGAGGGCAACCCCTGACTGCAGGTCTGATGCGGCCGTTATCCCTAACTGCTACTGGAAGGTTAGACGAGAAGGGGCA",
                   "TTGAGTGTGACACCAGTTGATTTGTTAGTGGCCTGGGTCACAGTGCCACCTGTGCCGGCTGAATAACCAACAGCAGATTCGGTGCTACCCAGCAGTGGTCGATTTAGATCATACACAGTGATGATATTGCCACCGTCCACAGTTGAAAATTCAAATTGATATGTTCCTGTAGCTGCAAAAGTGATCACATTTGATGCATACCCCTGAAGGCCTGTGATGCCC",
                   "GGAAAACTTACCAGGTCCGAACTCACTTGGGTATGACAATTTGATAGCGTTTTCACGAATTTGAGGGTAGTGGTGCATGGCCGTTCTTAGTTCGTGGATTGATTTGTCTGGTTAATTCCGATAACGAACGAGACTCAATTATTTAACTAGATACCTATCAGCTGTTGAAGTGCTGAAGTTGTGTGTTGCGTGTGGGTCTCGCAAGAGATTTACCGCGATATGCAATGGAGCTTCACCTGATAGTTTGGCTTTCGGCCTCGGTCGGTAAGCTTTATCTGCTTAAATAGACAAATTGCTTTCAGCAATATGAAATTGAGCA",
                   "GGAAAACTTACCAGGTCCGAACTTAATAGGGTAAGACAGATTAATAGCTCTTTCTCGAAATTAAGGGTAGTGGTGCATGGCCGTTCTTAGTTCGTGGAATGATTTGTCTGGTTAATTCCGATAACGAACGTGACTCAATCATATTAACTAGATACCTATCAGCTGTTGAAATGCTGAAGCTGTCAGTGTCGGTGCTGTGTGCTTGCTCTTAACGGGGTTTAGTTGCATGGTATTTGTACATTTGGCAGTGGAGTTTCACCTGATAGTTTGGTCAGGTCTCTTATGGGGGCTTTGGCTTTATCTGCTTAATAGGACAATTTGTGTTTAGCAAAATGAGATTGAGCA",
                   "CAGACCAGGCAACTTGGCCCCAGGGCCGCAGGCCCCGATGCCATAGTGAAGATCGTTAGCGAGATGCAGGGCATTGGCAGCACTGCCGCCATTCCCGCAGATATACACGTGGCGCCCTTCAATCCAGGCAGAGCGCAACGCCAGGGCCAGCTGCTCCACAGCCGCGAGCACATCAGCAGTGAAACAGTGCTGCAGGCGGCTGAGGTAAGCCTGCGCGAGGGGAAGAAAGCCGGGCGGGGCGCTGATCATTCTGAAATCGTAAGCAGTCTGTTGGCCTGTTGCAATGCGGCAGGGGTTCCAATGTCCAGATAAACATCGGTGGT",
                   "GGAAAACTTACCAGGTCCGAACTTAATAGGGTATGACAACTTGAGAGCGTTTTCTTGAAATTAAGGGTAGTGGTGCATGGCCGTTCTTAGTTCGTGGAATGATTTGTCTGGTTAATTCCGATAACGAACGAGACTCAATTATTTAACTAGATACCTATCAGCTGCTGAAATGCTGAAGCTTCATGGAGTGGCTCTTGTGTGCCAGCAATGGTATGCTTGGGTTTGTTCTGTGGAGTCGAGTTTCACCTGATAGTTTGGTCCCGGCTGTAGCAATATGGTCGGTGACTCTATCTTCTTAAAAAGACAAATTGCGTCTAGCAAAATGAAATTGAGCA",
                   "ACCAACAGGCATGAGATAAACATGCCCGGTGAATCCAGCGGCCCTGTACTCTTCAACTGCTCGTTCTGCATCTTGAAAGTCCTCTTCGGTGGCAACCACCAGTTTCAAATAGGTCACACCAACGTCTTCGTATTCACACACTATCTCAGGACAGATAGCATCTGACCATGACTCACCTGAGCCAGGCAGTTTGGCACTTACACTGAATGTAATCTCATTGTGTCCTGTGAGCCAGTTGCTGAGATAGTCTTTTAATTCTGGCGATAGTTTCTGTGTGCCATTGGTTTCAAATGTGATTTCTTTGAGTCTGGCCATGCTAGGATG",
                   "GGAAATGTTACCTGGATAGCACGAGGGCATGACATGACAGGCTGAATCCCTTTCTTAATGACTCGAAAAGTGGTGCATGGCCGTTCCTGGTTGGTGAAGTGATTTGTCTGGTTGATTCCGACAACGAACGAGGTCTTCACCTCTCAGTAGCCGGCGCTCTCGCTCGCAAGTAGGGTTTCTTAGTCCTCTGGGGGCAACCCTATGACTCTGGAATCCGAGAGCGGCGCTCGCTTCTCAGTGGGATCGGGCACTTTGTCCTCGGACTAAATGCCCATATCCGGAAGCCG",
                   "CGGGCACCGAGCGGCCGTTCACCGGCGAATACTGGAACGTGTTCGACGACGGCACCTACCGCTGCATCGTGTGCGATCTCGAGCTCTTCGACTCGTCAACCAAGTTCGACGCGCACTGCGGCTGGCCGAGCTTCTACGAGGCCCTCGACCGCGACCGTGTCCGGTTCATCGAGGATCGATCCCACGGGATGATTCGAGTCGAAGTGCGCTGCGCCGGATGTGATGCCC",
                   "CGGGCACCGAGCGGCCGTTCACCGGCGAATACTGGAATGTGTTCGACGACGGTACCTACCGCTGCATCGTGTGCGACCTCGAGCTCTTCGACTCGTCAACCAAGTTCGATGCGCACTGCGGCTGGCCGAGCTTCTACGAAGCCCTCGAGCGCGACCGCGTCCGGTTCATCGAGGATCGCTCCCACGGGATGATTCGCGTCGAAGTGCGCTGCGCCGGATGTGATGCCC",
                   "GGCCACCCAACCGCATTCTTCGAGGCTGACAAGGGTCTGACCTTTGATGTCCACCATCGCCCCTGTGAAGGGCTTTTCGTGGCCTCGCAGCTTTTTCAGCGCCGTCCACCTGGCGTGGGTTAATGTCGGTTTCATGCGATGCGGCCTTTGCTGTCTACAAGCCTGTCGGTTTCTCGCGCGATGCGAATGAGTGCTTCTCGGTCCAGGTCTGTGATGCCC",
                   "GGGAAACTCACGAGGTTAGTACGCTAAAATGCTTGACTGTTTGAAGTGCATTCAAAAGATAGCGAGTGGTGGTGCATGGCCGTTCTTGATTCGTAGAATGATTCGTCTGCTTAATTGCGATAACGAGTGAGACCTCGACCTATTAACTAGTTTATTTCATCATTTGGGATATAAAACGTTTATATGGTTTGATTGGTTGCTTTGGCAGGTTTGTTAGTTGTGTAGGGGTTTCGGCCAATGCATGATTGGCAGATTTGTTGGAGTAGCTGGCCGTATAGATAGGCCCTATGCTGAGATAAGACTTCTTAGAGGGATAAACGGTGTTTTAGCCGTAATAAATGAGGCA",
                   "CATGGGTCTGTACGTGTACCCCAGCCCGAACGTGACCCTGATTGGAGATACCGCCTGCAGCGGAGAAGAATTGTATTTCACCGGCAATGCCACGGTTAGTCCGGGCAATATCCAGCGTTATGAATGGGATTTTGGCGACGGTGGCACATCCACCCAGCAAAACCCCGTCCACACCTATACCTCCAGCGGAACTTTCACGCTCCGCCTTCGCGCTATCACCG",
                   "AAAAGAGCATCTGCGAACTGCTGTGGTCATGCACTACACTAGACTCAGTACGCACATTAGTCAGCGCACTGCCCCTGCGTGATCGCCAGGATGCACAGACTATCGTAACCCTGATGACTCAGGACAGCATTGAACTAGAGCTGGGTCTTGACCAGTATAAGGCACAGGCACAGTTAGCCATAGCACAGGCTAGACAGTAATGCGAGTGTATACTATAGCTGCTGCTCTACTGTGTACGCTGGC",
                   "AACAATCGGATCTATCGTGCCTATCAGGGCATTCCGTATGTCATCCCGACAGTCGCTATTGGCGGACGTTGGCCGTACACCTACAGCTTGAGCGGGCAGCCGTCTGGCATGACCATCGAGGCTGGCCCCTGCACAACCATTGGCACGTCCTGTACTGCCGGAACGATTACTTGGACCAGCCCCGACGCCACGGATTCGAGTATCACCGTGCAGGTCTGTGATGCCC",
                   "GCGCATACCTTCAAGGTGCTGCACATTGCGCTGGATCACGGTGTCGTCACCCGTGTAGCGGTTCGGGTTAGCGATGGCGTCGTTGATGACCCACACGCTGTCGAGACATGCCGAATAGTGCTTGGCAATCTGTTCAGGGGTCAGTTCTTCGGGGTTCATGGTTTTGCCTCCAGTTGGGCCTTCAGGGTTTTCACTTCTGCGGACAGGTCTGTGATGCCC",
                   "TTGGGGTAACAACTCCCGTGTTTGTTGAGAACTAACTTGGACAATGCCATTTTCATCAACGTCAACAAGAGCGGTATCGCCATCTTTGATGCGTCCAGACAGAATTTCTTCCGCCAAACTATCTTCCAATAAGCGCATAATTGCTCGACGTAATGGCCTTGCACCGTAGCTAGGACTGTAACCCTCAGTTATCAAGCGATCCTTGAAGCGGTCTGTGATGCCC",
                   "ATTGCGGTCGGTGCGCTCGAGAGCAGTAACGTCAATCCGGTCACTGCGATGGTGAAGCTGATTGATTTCTCGCGCTCCTATGAGACGCAGGTGCGGACGATCAAGGAAGCAAAATCACTCGACGAGTCCGGTGCCAGCATGCTCCGCACGCGAAACTAATGCACTGACTGAATAGATAAGAAAGAGGACATCATGGATGCATCAATGTGGGTAGCC",
                   "ATGCCATCACGGTATCACCCTATATGGGACGTGATTCGGTGGGACCGTTTTTGGAGGTCGCCGACCGGATGGTATATGTCTTGGCACTGACGTCGAACCCAGGTTCGCATGATTTTCAGCGTATGGAAATCGATGGACAGCCGCTGTATCGCAGAGTGATGGAATCGACGCTTTCCTGGCCGCGAAATGGAGACGTAGGGTTTGTTGTTGGGGCGACAAACGCAGATGAACTTGCCATGCTGCGTGGTGCATATCCAAACGTGCCACTCTTG",
                   "CGATGTAAAACTCTGTACGGTTCGCAATAACTGGCAAAGTGGTGTTCGCTTTGACATGTACAGACACAATATCAGTAGCAGTAACCCAACTGAAACCAATAACTTTGACCTGAGCGAAAGCAACATGATTGTATATGTGACCAGTACTGGATCAGTATACAAGTGTTTATTCAACGGTCGCAACGGCACCTTAACCTCGGGTGTTGTCAGCACAGTGATGCCC",
                   "AGTCCCGCGCCGAATGGAACAGGGTGGGTTCCCAGCACGGGCACACTGACGACCGCGACGACCATAGCGGTGGACCGGCAGTGGGGGGAGATCAACGCGGCAGTGAACTTCGGCGGCGTCCCCACTCTGGTGGCGTTCACCTTCAAGGCCCGCAGGGTGTCCGGCGGGTACACCTACTCTGTTGCGATGAACAACGGCACGCAGGTCTGTGATGCCC",
                   "AACTCGATCTGGCAGACGTAGTCGCCCGGCGTGTCGATCTCGGCAGCTGACGGGATGTACGCAATGCGCCCGTCCTCGCCGGCCTCGTTCTCGCCGACCACGATCTTCGTCATCGTCTCGCCGTCGATCTTGACCGCACCGGCATACGTCGCGAACAGCCGGCAAGTAATGTCCTCGCTCTGCAGGTCGATCGCCGCCGTGCTGTCTGTGATGCCC",
                   "GGGAAACTTACCAGGACCAGATGTTTTTTATGACTGACAGGCTTTGGGTCTTTCAGGATATTGCTTTTGGTGGTGCATGGCCGTTGGTGGTGCGTGGGTTGACCTGTCTAGCGTTGATTCAGCTAACGAGCGAGATTATCGCCAATTATTTACCATGATTTAGTTTTAAATTTATGGTTCTAATTGGGACTCCCTGCGATTTTAGCAGGTGGAAGAGGGTAGCA",
                   "CATCTCCCATACGCATGAGGAGATCGTCAATAGTCGTAACCCCTGTCAACGCCAACGGTTGTGGGCCAGAAGCGTTATCGGGAAGATTACCGTCATCCAACGCCATCAAACTCCCCCGGATTGTACGTGCTTGAGGTCATCCACAAACTTGCGTTTCTTGTAACTCAACTGCCCCTGCGTCATCTTGAACTTCTTCATGAGGTCTGTGATGCCC",
                   "GTCGATGATGAATTTGAGATTGATTGATGCAATTATGGCATTGATGACGGGTTCTAGCCCTTTGGTGGTGGGGCTTTGATCACAGATGGCACAGGCAGTGATGGTGAGCTTGATTACAACGGTACGTTGGTTGATGTTGTTGTGGGACCAGATGCGTCCTTTGGCATGGCGTAGAGAGAGGGTTTCCTTGTTGGAGGTGGTGTGGGTTTGCAGGTCTGTGATGCCC",
                   "AACACTTGATCTTGCAGAGCTCGGATTGCGTCCAAGTTGGTTTTTTGTCCTGCATCAGCAGCACCACCAGCACCCGGATCCGACTCAACCTGTGCGGTGGCTGCAGACAAATCTCGTTTGATGCGATCAACTCGTTTCAAAAATTCATCGCCCAGCAAGGGTTCATAACCCAAGTTCAGGAAATCGTTTTTCACTTGTTCGATTTGCCACTGCAGGTCTGTGATGCCC",
                   "GGGAAACTCACCGGGGCCACAGACTGGGATGAGCCACGTGGTGCCTCTGCATGGCGATTCAGTTGAAGGTGGTGCATGGCCGATTTTAGTTCGTGTCTTGAGATGTCTGGTTTATTCCGATAACGAGCGAGACTTGCAGACGACGCTGGGGGCGCGCTTTGTTTCAAAGAGTGCACCCCTCCCTCGTTGATATCCTCCAGTAAGGAGCGACAGCATGAGACGGCAAGCC",
                   "GGTCACCCAGCCGCATTCCTCCAGGCTGACGAGGGTCGGACCCTTGATGTCAAGTTCCGCCCCTGTGAACGTATTTTCGTGGTCTTGCAGCTTCTTTAGCGCCCGCCATCTGGCGTAAGTCAGTGTAGGTTTCATGCGATGCGGCCTTTGCTGTCTACAAGCCTGTCGGTTTCTCGCGCGATGCGGATCAGTGCTTCGCGGTCCAGGTCTGTGATGCCC",
                   "CAATCTCAATGGCTCCCTCAGGGACCTGACCGCGAGTGATTGACGCCTTTGCGGCAATTCCTGACTTTCGCAGGGAAGTCCTAAACAGGGTTCCCGCCTGCTGAATTGGCTTGTCGGTTCGCTTGCCGATGAAGTTCAAGGGTTTTGAGGAGCTCGTGAGTCTGGCAGCATCGATCTGCAGTGCAGAAATTGGTCCCATGTAGCCCTGCGAAATACCACGACG",
                   "ACTACAACGCCAAGTTCGGCTGGCCCTTCATCCTGGCCGTGCGTGGCCCGCGCGGCGTGGGCTTGAGCAAAAAACAGATCATCGAAGCCTTTGAGCGCCGTCTGTTCGGCCACCCCGACATGGAGTTGGCTGAGTGCCTGCGCAACATCCACCGCATCGTCGAGATCCGACTGAACGACAAATTTGGCGTGGAACCCACGCTGGGTCACCAGGTCTGTGATGCCC",
                   "CCCGGTGTTGACGTAACGCAAATTGCTGCCACTGAGGTCGGCATACGTAAACGTCGCGTTCAGTGCGAGGTCGCTCCAGACGACACCGCTCAATTTCTGGATCTTGCCGTAGTCCGGCAAATCGGTCAGCGTATAAGTCCAGCTGGCGTTGGCAGTATCCGGGTCACTGACATTCAGGATGCTCGTATTGAGCACCTGGATATGCGTGGTTTGCGCAGTGATGCCC",
                   "TCATCGTGAGGTCTTGGTGCATTTCGAGCGCAATCCTTTGAGTTGTTGCAGAGTGACCTCGTAGTGGTGTAAATTGTCCAGTTGATTTCAGCGTCCATCGTGCCGTTCAGCGTTTTTCTGTGGTGGACTTTGTAGTTTGGTTGCCGAACTAGGTTGGTGGTCGGTGTTGTGTGCTAGCTTCGTGTGGCAATTCCTCCCTTGTCCGCTCTAGCCTGTGATGCCC",
                   "GTTCAGTTTGTCTGTTCTCGGCTGCAATTCCCTGTCAGATAGGAATCAATCATATTAATGAGCAATGGCCTGATTATTGGAAGCAACACTTTCAGAAGAGAGGATATATACTTGTAGACTGTTTACGCTCCAAAATTTGGAATAATTCCAAAGTGGGTTGGTGGTATGCTCAAAATACCTTTCTATTTGTGAAACAAGAAGAATTAGCGAATTACCCTTTTCTACAAGCCGAATT",
                   "TGGGTCAGTAGTGTAGACACCATCAACATCTGTGTAGATTAGACACTCATCGGCCTTTAACGCGGCTGCCACAGCCACGGCGGAGGTATCAGAACCACCACGACCGAGCGTTGTGATGTGTCCTGCATCGTCGACACCCTGGAAGCCCGTCACCACGACGACACGCCCGGCATCAAGATCTGCGCGAATACGCTTATCGTCAATGGCGGTGATGCCC",
                   "TGTACGTGACTGCGCACAGTAGAGATCTGATCAAAAGTCGCACCTGCTACGGCCATAAGCTGGAAGTGAATAGGCATGAAGTACTCACCCACAATGTGCAAATCGGAGTGCGGCAGCAGGTGATGTATGTCGGCGACACGACCTGCGATTGAGTTCTCAATGGGGATCATCGCGAGATCAGCCGTGCCCTCTTCAAGAGCAGCGAATACATCTTCGAAGGTGGCGCAGG",
                   "AGATACTGTGAAGTTACCATTTGGCGGTGTACCGCCAGATGTTGTACCAAGAATCGCAACCTCATTACCTACAGAAAGACCGTGAGCAATTGGTGTTGTAACTGTTACATCTTGACCAGAGTAGGTCATTGTTGTAGCGGTATTGTTACCAATTACGGAGTCGCGATAGAAATCACCTTGAATAACAAGTGTTTTTGTCGCATCGTTAATTGACTGTGATGCCC",
                   "GGGAATCTCACCGGGGCCAGACTTGGGGAGGATTGACAGTTTGAGGTGCTTTCTTGATTTCAAGGGTGGTGGTGCATGGCCGCTTGAGTTCGTCTGATGACAGCGCTGGTTAATTCCGATAACGAGCAAGACTGTGTGGGTGGGTTTTGGGCCGCAGTCTTTGGACTGGCGGAGAGGATTTGCCCGACTGCGCATGAAGAGTGCGAGGAAGTACGCAGCC",
                   "TACTCAGGGGTCTGGCGCTCGGCCGCTTCTTTCTCGGCAGCGATGCGCTCTTGCTCGGCGGCTTCTTTGGCCAACACGTTGCGCTCGTCGCGCTCGGCCTTGGCTGCCTGTGTTTTGGCACCGCTGCGCTCTGTGTAACGGCCGATAGGTGCAAGCGTACCGCCCAGCACTGCGCCGCCGATGAAGCTGTCGATGTACTCTTTGCGGGCTTCTGGGTCTGTGATGCCC",
                   "GTGCGACTGTGCCGCGCGTCGGGCCTCGCCGAAGGCCTGGATCAGCTTCAGCTTGAGGTCTACGACTGTCGGCGTGTTCCTGCTCAGGGTCAGCACGAAGAACGCCTGATCCTCGTTCAGCAGTGCGAACCGCTCGCGCTGCCCGGTGCTGCTGCTCGCCGAAGCTCCTGTTTGAAACAGGACCTTTCCCAGCGCCAGCAGCTTGGCCTCGTACCGCTTGACCAGCT",
                   "CATGGAGCAGAAAAAAATCATGATTGAAAATCAGAAATTCCGTCCCTCACAGGTCGTTGGCCCGTTGGGCGAGCCGCTTACCCTAGATAGCCTGCCACCTGCTGGTACGACGCGCTGGGTCGTGCGCCGCAAGGCAGAGGTTGCCGCGGCCGTCAATGGTGGGTTATTGTCGATCAATGATGTCTGCGAACGTTACAACCTAACGCTTGAAGAATTTGCGTCATGGCAGCGCGCGG",
                   "GGGAAACTCACTAGGGCAAGAGGGGGGTAGGATGGACAGCCGATCAGGGCTTTCCTGATTCTTCCAGTGGTGGTGCATGGTCGTTCTTAGTTCGTGGATTGATTTGTCTGGTCTATTCCGCTAACGAGCGAGAACCCACCCTCTCGTGGTTAGGCGCCTGGGCATGCCCGTACCGCTCCGGCGGTGCGGGCTGAAAACGCCCTTGAGCTCGGTCCGGAGGGACCGTCTTCGACAAGGAGACGGCAGCGGGTCA",
                   "GGGAAACTTACGAGGTCAGGACAGGAGAAGGATTGACAGATTGAAGTTCTTTCAAGATTTTTTGGGTGGTGGTGCATGGCCGTTCTTAGTTAGTGTTGTGAAATGTCTGCTTTATTGCGATAACTAGCGAGACCACTGCGGCATAGTACGACGAGTCAGTGAGCAATTGCTGGCCCGCTTCGATTTTGCCGGACAACCCGTGTTTAACGGGAGGAAGTTGGTGGCG",
                   "AGCATGGTGGCGCCGGAGGCCAGGGCCCCGGGCAGCATCAGCAAACCGGTTTGGATCGCCGTGAAGTGCAGCACACCCTGGGCAAAGATCGGAATCAGAAAAACCGTGCCATAAAGGCCAATCCCGACGATCATCGAGAGAATGCTGCCGGCCGCCAAGCTGCGGTGACGCAGCACCCTGAGCTGCACGGCTGGGGTTGGATGGCGGAGCTCCCACCAAATAAAAGCGGGACA",
                   "ACAGCACAAGCTAATTCAGCCGATGGATTACTAAAGTACATCTCAAGCGCTGCTGCTGCTGTTTATTCAGCATCACTTGGATTTGCTCGTAACATTGTAGTTACACCAGCACAATGGGCAAACATCATGTCATACAACGATAACGGACGACCAATCTACATTGCTGCAAACCCTCAAAACGCAGGTGGTGCACTTTCACCTCTTAGCGTTCGTGGTTC",
                   "CAGGCCACTCCTTCGGCGACTTTTTCGGTCGAACTCGCGAAGGGCTGTATGTCGATACGCGGCGTTCCATGTTGAAAGCCGGGATGGCCGGAATGGCCGGTCTTTCGTTGCCGGGTTTACTTCAGGCCAAAGCCGAAGCGGCTGCTGCAGGAACCTCTGGGCCGACTGGCAAAAGTGTGATCCTGTTATGGATGGCCGGTGGTCCAAGCCACATTGATACCTGGGACAGTAAGCCGGATCGTCCGTGGGTCAATCGAGGTCCATTTGGTGTCACGAGAACCAAATTGCCGGGCGTTGTGATTTGTGAGCATTTGCCGAAGCAGGCTGCAATGCTGGACAAGTTCACG",
                   "GGGAAACTTACCAGGTCGAAACATGGTGAGGATTGGAGTGATTTGTCTGGTTAATTCCGTTAACGAACGAGACCCCCGCCTACTAAATAGTGTGGGTAATGCTTATGCATTGCCTTTTCTACTTCTTCGAGGGGCTTTCAGTGACTAACCTCACCTTGCAAGTCCTTATTAGCTCAGTGTTTCAAATATCGGGCTTGGTTCAAACACACCTTCCTTTTTGGGAGTTTAGCATTTAACTGAAGGAAGTTGGGGCA",
                   "GGCTGTATCGGAGTACGTTGGCGTCTTCCAGCGTCTTGCTGATGTCCTTGAAGTATTCCGTTTTGTCCATGCGGCTGTCCACGCCCGCCAGTCTCGTGATCCTTAGGTGAGGGGCGCGTCTCTCGGTGTCATCCGTGATGCTCAGAGCCTGTCCTGAGCTTGGATTGGCCCCGCGTACTCTGAATCTTGGAGTCTCTTTGCACAAGGTCTCAAGCAACTTCACGGAGCTACACATGGCGTTGCCTCGCTCGTTGCGCTCGCTATTCACATTATTGGCATAGAGCATGTC",
                   "GCCATGGCTCCAGCACAGGCACAGTATGAACAGAACTTGGCACAACAGCAGGCACAGTTTGGTGGCTCTGGCAACTTGGGTTCAGCACGACAGGCTCTGGCAGGACGACAGTTGGCCGGCCAAACACAGTCAGCACAGGCTGCCACAGCGGCCAACATACTCAAAGACATTTCTGCACAACGAGCACAAGTTGGCGGCACACTAGCACAACTGGGTC"
)

# Spurious ASVs as identified from MAFFT alignment:
# "ASV01583", "ASV06846", "ASV10690", "ASV11623", "ASV11855",
# "ASV12895", "ASV13329", "ASV13519", "ASV13731", "ASV14132",
# "ASV14757", "ASV15008", "ASV15684", "ASV15716", "ASV15879",
# "ASV16213", "ASV16236", "ASV16265", "ASV16317", "ASV16428",
# "ASV16531", "ASV16553", "ASV16555", "ASV16711", "ASV16718",
# "ASV16733", "ASV16747", "ASV16844", "ASV16859", "ASV16860",
# "ASV16867", "ASV16893", "ASV16915", "ASV16920", "ASV16922",
# "ASV16926", "ASV16959", "ASV16961", "ASV16965", "ASV16967",
# "ASV16968", "ASV16971", "ASV16975", "ASV16978", "ASV16990",
# "ASV17010", "ASV17045", "ASV17047", "ASV17056", "ASV17063",
# "ASV17065", "ASV17066", "ASV17067", "ASV17084", "ASV17087",
# "ASV17097"

# Remove spurious ASVs from dataset
asv_melt <- asv_melt %>%
  filter(!sequence %in% asvs_spurious)
length(unique(asv_melt$asv_code))  # n ASVs


#### Write new files for retained ASVs ####
asv_rmspurious <- asv_melt %>%
  distinct(asv_code, sequence) %>%
  arrange(asv_code)

# Write new fasta file for retained ASVs
# write.fasta(sequences = as.list(asv_rmspurious$sequence),
#             names = asv_rmspurious$asv_code,
#             file.out = "output/fasta/lp2017-2019watercolumn18s_rmspurious.fasta")

# Write new melted ASV table for retained ASVs
# asv_melt %>%
#   write_tsv("output/melted/lp2017-2019watercolumn18s_melt_rmspurious.tsv")
